services:
  rails_server:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && bundle exec rails s -b '0.0.0.0'"
    image: ruby_nos_trilhos:v1.0
    container_name: ruby_server
    volumes:
      - '.:/usr/ruby_nos_trilhos'
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db
    environment:
      - DB_USERNAME=${POSTGRES_USERNAME}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_PORT}
    ports:
      - '${PGADMIN_PORT}:${PGADMIN_PORT}'
    depends_on:
      - postgres_db

volumes:
  postgres_data:
