default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  primary:
    <<: *default
    database: quadrovagas-development
  queue:
    <<: *default
    database: quadrovagas-queue_development
    migrations_path: db/queue_schema

test:
  primary:
    <<: *default
    database: quadrovagas-test
  queue:
    <<: *default
    database: quadrovagas-queue_test
    migrations_path: db/queue_schema

production:
  <<: *default
  database: quadrovagas-production
